conan: dynamic conan remote login from conan-context

diff --git a/.github/workflows/conan-library.yml b/.github/workflows/conan-library.yml
--- a/.github/workflows/conan-library.yml
+++ b/.github/workflows/conan-library.yml
@@ -149,6 +149,8 @@ jobs:
           path: .conan-context
       - name: Configure Conan
         run: |
+          all_secrets='${{ tojson(secrets) }}'
+          
           git config --global url."https://github.com/".insteadOf git@github.com:
           
           organisations=$(yq -r '.organisations[]' ${CONAN_CONTEXT_PATH})
@@ -164,14 +166,13 @@ jobs:
             echo "Skip conan git credentials configuration"
           else
             echo "Start conan git credentials configuration"
-            all_secrets='${{ tojson(secrets) }}'
             for org in $organisations; do
               secret_to_extract=$(echo $org | tr '[:lower:]' '[:upper:]' | tr '-' '_')_GIT_TOKEN
               echo "Extracting github secret $secret_to_extract for organisation $org"
               secret=$(echo $all_secrets | jq -r ".$secret_to_extract")
               if [ "null" = "$secret" ]; then
                 echo "Secret $secret_to_extract not found !"
-                echo "Please add secret $secret_to_extract to https://github.com/organizations/$org/settings/secrets/actions"
+                echo "Please add secret $secret_to_extract to https://github.com/organizations/${GITHUB_REPOSITORY_OWNER}/settings/secrets/actions"
                 exit 1
               else
                 echo "Secret $secret_to_extract found !"
@@ -194,11 +195,50 @@ jobs:
             conan_config_branch="main"
           fi
           echo "Will use conan_config_url: ${conan_config_url}, conan_config_branch: ${conan_config_branch}"
-  
           conan config install "${conan_config_url}" --args="-b ${conan_config_branch}"
+          
+          echo "Start conan remotes configuration"
+          repositories=$(yq eval '.repositories' ${CONAN_CONTEXT_PATH} -o=json | jq)
   
-          conan remote login -p "$ARTIFACTORY_TOKEN" "VOQA-SNAPSHOTS" "$ARTIFACTORY_USERNAME"
-          conan remote login -p "$ARTIFACTORY_TOKEN" "VOQA-RELEASES"  "$ARTIFACTORY_USERNAME"
+          if [ "null" = "$repositories" ]; then
+            echo "Field repositories is missing in ${CONAN_CONTEXT_PATH}"
+            echo "Please set it"
+            exit 1
+          fi
+  
+          if [ -z "$repositories" ]; then
+            echo "Field repositories is empty in ${CONAN_CONTEXT_PATH}"
+            echo "Skip conan remote configuration"
+          else
+            for kv in $(echo $repositories | jq -r 'to_entries[] | "\(.key)=\(.value)"'); do
+              repo_name=${kv%%=*}
+              repo_url=${kv#*=}
+            
+              echo "Add conan remote ${repo_name}: ${repo_url}"
+              conan remote add "${repo_name}" "${repo_url}"
+              
+              echo "Add conan authentication for ${repo_name}"
+              repo_url_target=$(echo $repo_url | sed -e 's/https:\/\///' -e 's/\/.*//')
+              secret_username_to_extract="REPOSITORY_USERNAME_$(echo $repo_url_target | tr '[:lower:]' '[:upper:]' | tr '.' '_' | tr '-' '_')"
+              echo "Extracting github secret ${secret_username_to_extract}"
+              secret_username=$(echo $all_secrets | jq -r ".${secret_username_to_extract}")
+              if [ "null" = "${secret_username}" ]; then
+                echo "Secret ${secret_username_to_extract} not found !"
+                echo "Please add secret ${secret_username_to_extract} to https://github.com/organizations/${GITHUB_REPOSITORY_OWNER}/settings/secrets/actions"
+                exit 1
+              fi
+              secret_token_to_extract="REPOSITORY_TOKEN_$(echo $repo_url_target | tr '[:lower:]' '[:upper:]' | tr '.' '_' | tr '-' '_')"
+              echo "Extracting github secret ${secret_token_to_extract}"
+              secret_token=$(echo $all_secrets | jq -r ".${secret_token_to_extract}")
+              if [ "null" = "${secret_token}" ]; then
+                echo "Secret ${secret_token_to_extract} not found !"
+                echo "Please add secret ${secret_token_to_extract} to https://github.com/organizations/${GITHUB_REPOSITORY_OWNER}/settings/secrets/actions"
+                exit 1
+              fi
+              conan remote login -p "${secret_token}" "${repo_name}" "${secret_username}"
+            done
+          fi
+          all_secrets=''
       - run: bash test.sh
       - name: Extract test report
         run: |
