Update collector topology with rebuild target

diff --git a/.github/workflows/conan-library.yml b/.github/workflows/conan-library.yml
--- a/.github/workflows/conan-library.yml
+++ b/.github/workflows/conan-library.yml
@@ -663,7 +663,8 @@ jobs:
 
           # ONE COLLECTOR
           if [ "$COLLECTOR_TOPOLOGY" = "{}" ] || [ -z "$COLLECTOR_TOPOLOGY" ]; then
-            echo "One collector collectors-list=$COLLECTORS" >> "$GITHUB_OUTPUT"
+            echo "No collector topology configured."
+            echo "collectors-list=$COLLECTORS" >> "$GITHUB_OUTPUT"
             exit 0
           fi
 
@@ -724,13 +725,20 @@ jobs:
           
           if [ "$BUILD_MISSING" != "true" ]; then
             if  [ -n "$REBUILD_TARGET" ]; then
+                # Check if REBUILD_TARGET valid
+                if ! jq -e --arg target "$REBUILD_TARGET" \
+                  'has($target) or any(.[]?.children[]?; . == $target)' \
+                  <<< "$COLLECTOR_TOPOLOGY" >/dev/null; then
+                  echo "ERROR: Unknown rebuild target: $REBUILD_TARGET"
+                  exit 1
+                fi
                 # Use specified rebuild target when specified
                 selected=$(jq -cn --arg target "$REBUILD_TARGET" '[$target]')
-                echo "Using rebuild target: $REBUILD_TARGET"
+                echo "Using rebuild target collector: $REBUILD_TARGET"
             else
                 selected="$FIRST_LEVEL_COLLECTORS"
-                echo "No rebuild target defined."
-                echo "Fallback to first-level collectors: $FIRST_LEVEL_COLLECTORS"
+                echo "No rebuild target defined - using first-level collectors:"
+                echo "$FIRST_LEVEL_COLLECTORS" | jq .
             fi
             echo "collectors-list=$selected" >> "$GITHUB_OUTPUT"
             exit 0
