intercept already exist error on branch creation

diff --git a/.github/workflows/conan-context-delivery.yml b/.github/workflows/conan-context-delivery.yml
--- a/.github/workflows/conan-context-delivery.yml
+++ b/.github/workflows/conan-context-delivery.yml
@@ -497,14 +497,13 @@ jobs:
                   "/repos/${URL_REL}/git/refs" \
                   -f "ref=refs/heads/release/${DELIVERY_NAME}" \
                   -f "sha=${sha}"
-                gh api --method POST \
-                  -H 'Accept: application/vnd.github+json' \
-                  -H 'X-GitHub-Api-Version: 2022-11-28' \
-                  "/repos/${URL_REL}/git/refs" \
-                  -f "ref=refs/heads/release/${DELIVERY_NAME}" \
-                  -f "sha=${sha}"
-
-                : # curl --fail -X POST -H "Authorization: token ${OWNER_GIT_TOKEN}" -d  "{\"ref\": \"refs/heads/release/${DELIVERY_NAME}\",\"sha\": \"$sha\"}" "https://api.github.com/repos/$URL_REL/git/refs"
+                res=$(gh api --method POST -H 'Accept: application/vnd.github+json' -H 'X-GitHub-Api-Version: 2022-11-28' "/repos/${URL_REL}/git/refs" -f "ref=refs/heads/release/${DELIVERY_NAME}" -f "sha=${sha}")
+                if  [ $? ]; then
+                        if [ "$(echo $res| jq -r .message)" != "Reference already exists" ]; then
+                                echo "ERROR $res"
+                                exit 1
+                        fi
+                fi 
               fi
 
               : # ---------- UPLOAD ARTEFACT TO CONAN REPOSITORY -----------
