Usevar from context toretrieve ALM credentials

diff --git a/.github/workflows/conan-context-delivery.yml b/.github/workflows/conan-context-delivery.yml
--- a/.github/workflows/conan-context-delivery.yml
+++ b/.github/workflows/conan-context-delivery.yml
@@ -337,27 +337,50 @@ jobs:
             echo "No 'almRelease' in conan context : skipping ALM release creation"
             exit 0
           fi
+          # Retrieve url username and password
+          almUrl=$(yq -r ".almRelease.almUrl" "${CONAN_CONTEXT_PATH}")
+          all_secrets='${{ tojson(secrets) }}'
+          username_secret_var=$(yq -r ".almRelease.almUsernameSecret" "${CONAN_CONTEXT_PATH}")
+          password_secret_var=$(yq -r ".almRelease.almPasswordSecret" "${CONAN_CONTEXT_PATH}")
+          username_secret=$(echo "$all_secrets" | jq -r ".${username_secret_var}")
+          password_secret=$(echo "$all_secrets" | jq -r ".${password_secret_var}")
+          if [ -z "${username_secret}" ] || [ "null" = "${username_secret}" ]; then
+            echo "Secret ${username_secret_var} not found !"
+            echo "Please add secret ${username_secret_var} to https://github.com/organizations/${GITHUB_REPOSITORY}/settings/secrets/actions"
+            exit 1
+          else
+            echo "Found secret ${username_secret_var}"
+          fi
+          if [ -z "${password_secret}" ] || [ "null" = "${password_secret}" ]; then
+            echo "Secret ${password_secret_var} not found !"
+            echo "Please add secret ${password_secret_var} to https://github.com/organizations/${GITHUB_REPOSITORY}/settings/secrets/actions"
+            exit 1
+          else
+            echo "Found secret ${password_secret_var}"
+          fi
+
+
           echo "!!!! deliverable=$deliverable !!!!!!"
           echo "Create ALM release"
-          almcli checkRelease --log=INFO --releaseFile="${CONAN_CONTEXT_PATH}" --username="${{secrets.ALM_USERNAME}}" --password="${{secrets.ALM_PASSWORD}}" --url="https://webadmin.api.dpu.prod.assurenextgen.com"
+          almcli checkRelease --log=INFO --releaseFile="${CONAN_CONTEXT_PATH}" --username="${{username_secret}}" --password="${{password_secret}}" --url="${{almUrl}}"
           res=$?
           if [ "${res}" = "0" ]; then
             echo "Release already exists, skipping creation"
             exit 0
           else
             echo "Release does not exist or is different, try creating it"
-            almcli createRelease --log=INFO --releaseFile="${CONAN_CONTEXT_PATH}" --username="${{secrets.ALM_USERNAME}}" --password="${{secrets.ALM_PASSWORD}}" --url="https://webadmin.api.dpu.prod.assurenextgen.com"
+            almcli createRelease --log=INFO --releaseFile="${CONAN_CONTEXT_PATH}" --username="${{username_secret}}" --password="${{password_secret}}" --url="${{almUrl}}"
             res=$?
             if [ "${res}" != "0" ]; then
               echo "almcli createRelease failed, try update"
-              almcli updateRelease --log=INFO --releaseFile="${CONAN_CONTEXT_PATH}" --username="${{secrets.ALM_USERNAME}}" --password="${{secrets.ALM_PASSWORD}}" --url="https://webadmin.api.dpu.prod.assurenextgen.com"
+              almcli updateRelease --log=INFO --releaseFile="${CONAN_CONTEXT_PATH}" --username="${{username_secret}}" --password="${{password_secret}}" --url="${{almUrl}}"
               res=$?
               if [ "${res}" != "0" ]; then
                 echo "almcli updateRelease failed"
                 exit 1
               fi
             fi
-            almcli publishRelease --log=INFO --releaseFile="${CONAN_CONTEXT_PATH}" --username="${{secrets.ALM_USERNAME}}" --password="${{secrets.ALM_PASSWORD}}" --url="https://webadmin.api.dpu.prod.assurenextgen.com"
+            almcli publishRelease --log=INFO --releaseFile="${CONAN_CONTEXT_PATH}" --username="${{username_secret}}" --password="${{password_secret}}" --url="${{almUrl}}"
             res=$?
             if [ "${res}" != "0" ]; then
               echo "almcli publishRelease failed"
