add logs

diff --git a/.github/workflows/conan-context-delivery.yml b/.github/workflows/conan-context-delivery.yml
--- a/.github/workflows/conan-context-delivery.yml
+++ b/.github/workflows/conan-context-delivery.yml
@@ -261,11 +261,19 @@ jobs:
               rm -f gpg_key_base64.txt gpg_key.pem
               # Create the nexus repository
               echo "repo: $APT_REPO_NAME store: $NEXUS_APT_REPO_BLOBSTORE policy: $APT_REPO_WRITE_POLICY distri: $NEXUS_APT_DISTRIBUTION_NAME"
-              curl --fail --header "Content-Type: application/json" \
+              response=$(curl --fail -o output.json --header "Content-Type: application/json" \
                 -u "${{secrets.REPOSITORY_USERNAME_REPOSITORY_NEXUS_VIXTECHNOLOGY_COM}}:${{secrets.REPOSITORY_TOKEN_REPOSITORY_NEXUS_VIXTECHNOLOGY_COM}}" \
                 "${NEXUS_URL}/service/rest/v1/repositories/apt/hosted/" \
                 -d "{  \"name\": \"${APT_REPO_NAME}\", \"online\": true, \"storage\": {\"blobStoreName\": \"${NEXUS_APT_REPO_BLOBSTORE}\",\"strictContentTypeValidation\": true,\"writePolicy\": \"${APT_REPO_WRITE_POLICY}\"}, \
-                \"apt\": {\"distribution\": \"${NEXUS_APT_DISTRIBUTION_NAME}\"}, \"aptSigning\": { \"keypair\": \"${key}\",\"passphrase\": \"${{ secrets.APT_GPG_PASSPHRASE }}\"}}"
+                \"apt\": {\"distribution\": \"${NEXUS_APT_DISTRIBUTION_NAME}\"}, \"aptSigning\": { \"keypair\": \"${key}\",\"passphrase\": \"${{ secrets.APT_GPG_PASSPHRASE }}\"}}")
+              if [ "${response}" = "200" ]; then
+                echo "Apt repo created"
+              else
+                echo "Failed to create apt repo"
+                echo "Http error: ${response}"
+                echo "Response output:"
+                exit 1
+              fi
             else
               echo "Repository ${APT_REPO_NAME} cannot be found. But error is not 404."
               echo "Http error: ${response}"
